FROM python:3.12-slim

ENV BASE_URL="https://api.openai.com/v1"
ENV API_KEY=""
ENV MODEL_NAME="gpt-3.5-turbo"
ENV TEMPERATURE="0.0"
ENV MAX_TOKENS="2048"
ENV FREQUENCY_PENALTY="1.1"
ENV PRESENCE_PENALTY="1.1"
ENV HOST="0.0.0.0"
ENV PORT="5000"
ENV USE_HISTORY="1"
ENV MAX_HISTORY="20"
ENV USE_LATEST_HISTORY="1"
ENV DB_TYPE="sqlite"
ENV CACHE_TRANSLATION="1"
ENV USE_CACHED_TRANSLATION="1"
ENV USE_LATEST_RECORDS="1"
ENV INIT_LATEST_RECORDS="1"
ENV POSTGRES_HOST="localhost"
ENV POSTGRES_PORT="5432"
ENV POSTGRES_USER=""
ENV POSTGRES_PASSWORD=""
ENV POSTGRES_DB="xunity"
ENV SQLITE_DB_PATH="translation.db"
ENV LOG_FILE=""
ENV LOG_LEVEL=""
ENV TASK_TEMPLATE=""
ENV SPECIFY_LANGUAGE="1"
ENV LANGUAGE_TEMPLATE=""
ENV SRC_START=""
ENV SRC_END=""
ENV TGT_START=""
ENV TGT_END=""
ENV USE_SYSTEM_PROMPT="1"
ENV SYSTEM_PROMPT=""
ENV CONFIG=""

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x start.sh
CMD ["./start.sh"]